In [1]:
from pathlib import Path
import pandas as pd

ROOT = Path.cwd().parents[1]
DATA_RAW = ROOT / "data_raw"

POINTS_RAW  = DATA_RAW / "points_raw"
MATCHES_RAW = DATA_RAW / "matches_raw"

assert POINTS_RAW.exists()
assert MATCHES_RAW.exists()

print("Project root:", ROOT)

Project root: /Users/leventezsiga/Documents/Documents - Levente’s MacBook Air/VU/Thesis_P2-P3/tennis-pressure

In [2]:
points_files = sorted(POINTS_RAW.glob("*.csv"))
matches_files = sorted(MATCHES_RAW.glob("*.csv"))

print("Points files:", len(points_files))
print("Matches files:", len(matches_files))

Points files: 49
Matches files: 49

In [3]:
points_sample_file = points_files[0]
points_df = pd.read_csv(points_sample_file)

print("POINTS columns:")
for c in points_df.columns:
    print(c)

print("\nPOINTS sample rows:")
points_df.head(3)

POINTS columns:
match_id
ElapsedTime
SetNo
P1GamesWon
P2GamesWon
SetWinner
GameNo
GameWinner
PointNumber
PointWinner
PointServer
Speed_KMH
Rally
P1Score
P2Score
P1Momentum
P2Momentum
P1PointsWon
P2PointsWon
P1Ace
P2Ace
P1Winner
P2Winner
P1DoubleFault
P2DoubleFault
P1UnfErr
P2UnfErr
P1NetPoint
P2NetPoint
P1NetPointWon
P2NetPointWon
P1BreakPoint
P2BreakPoint
P1BreakPointWon
P2BreakPointWon
P1FirstSrvIn
P2FirstSrvIn
P1FirstSrvWon
P2FirstSrvWon
P1SecondSrvIn
P2SecondSrvIn
P1SecondSrvWon
P2SecondSrvWon
P1ForcedError
P2ForcedError
History
Speed_MPH
P1BreakPointMissed
P2BreakPointMissed
ServeIndicator
P1TurningPoint
P2TurningPoint

POINTS sample rows:

,match_id,ElapsedTime,SetNo,P1GamesWon,P2GamesWon,SetWinner,GameNo,GameWinner,PointNumber,PointWinner,...,P2SecondSrvWon,P1ForcedError,P2ForcedError,History,Speed_MPH,P1BreakPointMissed,P2BreakPointMissed,ServeIndicator,P1TurningPoint,P2TurningPoint
0,2011-ausopen-1101,00:00:00,1.0,0.0,0.0,0,1.0,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
1,2011-ausopen-1101,0:00:00,1.0,0.0,0.0,0,1.0,0,1,1.0,...,0.0,0.0,0.0,21020.0,103.0,0,0,2,0,0
2,2011-ausopen-1101,0:00:23,1.0,0.0,0.0,0,1.0,0,2,1.0,...,0.0,0.0,0.0,22020.0,82.0,0,0,2,0,0

In [4]:
matches_sample_file = matches_files[0]
matches_df = pd.read_csv(matches_sample_file)

print("MATCHES columns:")
for c in matches_df.columns:
    print(c)

print("\nMATCHES sample rows:")
matches_df.head(3)

MATCHES columns:
match_id
year
slam
match_num
player1
player2
status
winner
event_name
round
court_name
court_id
player1id
player2id
nation1
nation2

MATCHES sample rows:

,match_id,year,slam,match_num,player1,player2,status,winner,event_name,round,court_name,court_id,player1id,player2id,nation1,nation2
0,2011-ausopen-1101,2011,ausopen,1101,Rafael Nadal,Marcos Daniel,Retired,1,Men's Singles,Round 1,Rod Laver Arena,A,atpn409,atpd339,ESP,BRA
1,2011-ausopen-1103,2011,ausopen,1103,Bernard Tomic,Jeremy Chardy,Complete,1,Men's Singles,Round 1,Hisense Arena,B,atpta46,atpca12,AUS,FRA
2,2011-ausopen-1105,2011,ausopen,1105,John Isner,Florent Serra,Complete,1,Men's Singles,Round 1,Court 6,H,atpi186,atps963,USA,FRA